server/src/prueba.tsx
Por favor apruebenme el cambio, gracias.
=> prueba branchDenis

server/totalgames.json
JSON con los datos de los juegos totales para crear la base de datos
=> totalgames.json done

server/package-lock.json, server/package.json, server/src/app.js, server/src/routes/index.js
=> finalizada la base de datos

client/package-lock.json, client/src/App.tsx, client/src/components/NavBar/NavBar.style.ts, client/src/components/NavBar/NavBar.tsx, client/src/pages/Home/Home.tsx, server/totalgames.json
=> Json minor fixes

client/package-lock.json, client/src/App.tsx, client/src/components/NavBar/NavBar.style.ts, client/src/components/NavBar/NavBar.tsx, client/src/pages/Home/Home.tsx
=> rendered cart with navlink

client/src/App.tsx, client/src/components/Card/Card.style.ts, client/src/components/Paginate/Paginate.tsx, client/src/components/index.ts, client/src/pages/Cart/Cart.tsx, client/src/pages/Home/Home.tsx, client/src/pages/index.ts, client/src/redux/actions/index.ts, client/src/redux/actions/mock.ts, client/src/redux/reducer/index.ts
Agregamos archivo Mock con todos los juegos, Paginate listo ✔️ y top 0 a la card
=> Paginate-Mock-CardTop0

client/package-lock.json, client/package.json, client/public/index.html, client/src/App.tsx, client/src/GlobalStyles/GlobalStyles.ts, client/src/components/Card/Card.tsx, client/src/components/NavBar/NavBar.tsx, client/src/interfaces/index.ts, client/src/pages/Detail/Detail.tsx, client/src/pages/Home/Home.tsx, client/src/pages/index.ts, client/src/redux/actions/index.ts, client/src/redux/actions/mock.ts, client/src/redux/reducer/index.ts, client/src/redux/types/index.ts
=> detail route added

server/index.js, server/src/routes/index.js, server/totalgames.js
=> rutas del back nuevas

data_contract.md
Agregue un archivo .md al root de proyecto con las buenas practicas a seguir 😎
=> feat(proyecto): Data Contract

client/src/components/Filter/Filter.tsx, client/src/components/index.ts, client/src/interfaces/index.ts, client/src/pages/Home/Home.tsx, client/src/redux/actions/products_action.ts, client/src/redux/reducer/cartReducer.ts, client/src/redux/reducer/productsReducer.ts, client/src/redux/types/index.ts
=> feat(Filter) filtrado por plataformas

client/src/components/Filter/Filter.tsx, client/src/pages/Home/Home.tsx, client/src/redux/actions/products_action.ts, client/src/redux/reducer/productsReducer.ts, client/src/redux/types/index.ts
=> genreFilter added

client/src/components/SearchBar/SearchBar.tsx, client/src/pages/Home/Home.tsx, client/src/redux/reducer/productsReducer.ts
Se corrigió un bug del SearchBar al momento de actualizar el el currentPage(paginado)
=> fix(SearchBar)actualiza paginado

client/src/components/Filter/Filter.tsx, client/src/pages/Home/Home.tsx, server/index.js
on sale toggle completo y funcionando
=> on sale toggle completo

client/src/App.tsx, client/src/components/Forms/FormProduct.tsx, client/src/interfaces/index.ts, client/src/redux/actions/products_action.ts
=> form mejorado

client/src/GlobalStyles/GlobalStyles.ts, client/src/Theme.tsx, client/src/assets/img/svg/close-transparent.svg, client/src/components/ButtonTheme/ButtonTheme.style.ts, client/src/pages/CartSideBar/CartSideBar.tsx, client/src/pages/CartSideBar/StyledCartSideBar.ts
Modifique el componente Cart para que se muestre lo que podemos necesitar   https://i.imgur.com/KNSuU0O.png
=> fix(css/front): mejora de la UI del carrito

client/src/GlobalStyles/GlobalStyles.ts, client/src/components/ProductCard/Mini.tsx, client/src/components/ProductCard/ProductCard.tsx, client/src/pages/CartSideBar/CartSideBar.tsx, client/src/pages/ProductDetail/ProductDetail.tsx, client/src/pages/ProductDetail/StyledProductDetail.tsx
falta restar cantidad del carrito
=> fix(cart): funciona agregar por cantidad y actualizar precio

client/src/components/ProductCard/Mini.tsx, client/src/components/ProductCard/ProductCard.tsx, client/src/pages/CartSideBar/CartSideBar.tsx, client/src/pages/ProductDetail/ProductDetail.tsx, client/src/redux/actions/cart_actions.ts, client/src/redux/reducer/cartReducer.ts, client/src/redux/types/index.ts
=> fix(cart): botones ahora funcionan bien

client/package-lock.json, client/src/components/Forms/FormProduct.tsx, server/package-lock.json
Vista previa de imágenes y posibilidad de eliminar las mismas en el formulario de creación de producto.
=> Fix(ProductCreateForm)vista previa de img agregadas

server/src/controllers/Genre.js, server/src/controllers/Platform.js, server/src/controllers/Product.js, server/src/models/Genre.js, server/src/models/Platform.js, server/src/models/Product.js
validaciones en bases de datos
=> Feat(Model/product - genres - platforms)validaciones en bases de datos

client/src/App.tsx, client/src/GlobalStyles/GlobalStyles.ts, client/src/components/Footer/Footer.tsx, client/src/components/Footer/StyledFooter.tsx, client/src/components/NavBar/NavBar.tsx, client/src/components/NavBar/StyledNavBar.ts, client/src/components/Title/Title.style.ts, client/src/components/Title/Title.tsx, client/src/pages/FormLogin/FormLogin.tsx
=> navbarModal user

client/src/components/NavBar/NavBar.tsx, client/src/components/ProductCard/Mini.tsx, client/src/pages/ProductDetail/ProductDetail.tsx, client/src/redux/reducer/cartReducer.ts
el carritoo lleno de funcionalidaaaad
=> carrito con full funcionalidad

client/src/GlobalStyles/GlobalStyles.ts, client/src/components/ProductCard/ProductCard.tsx, client/src/pages/ProductDetail/ProductDetail.tsx, client/src/redux/reducer/cartReducer.ts
=> carrito mega archi funcional esta vez si

client/package-lock.json, client/src/components/ProductContent/ProductContent.style.ts, client/src/components/SalesContent/SalesContent.style.ts, client/src/components/SalesContent/SalesContent.tsx, client/src/components/UserContent/UserContent.style.ts, client/src/components/UserContent/UserContent.tsx, client/src/interfaces/index.ts, client/src/pages/AdminPanel/AdminPanel.style.ts, server/package-lock.json
pura calidad 100% real no fake, real hasta la muerte #freeanuel
=> arreglando admin funcional top class master ultra

client/package-lock.json, client/src/App.tsx, client/src/components/ProductContent/ProductContent.tsx, client/src/components/SalesContent/SalesContent.tsx, client/src/components/UserContent/UserContent.tsx, client/src/interfaces/index.ts, client/src/pages/UserOrderDetail/UserOrderDetail.tsx, server/index.js, server/src/controllers/Order.js, server/src/controllers/Product.js, server/src/routes/Auth.js, server/src/routes/Genre.js, server/src/routes/Platform.js, server/src/routes/Product.js
=> si sos pending no podes dejar reviu paaa

client/src/App.tsx, client/src/GlobalStyles/GlobalStyles.ts, client/src/components/AdminHome/AdminHome.tsx, client/src/components/Favorites/Favorites.tsx, client/src/components/LogOut/LogOut.tsx, client/src/components/NavBar/NavBar.tsx, client/src/components/PanelCatalog/PanelCatalog.tsx, client/src/components/ProductCard/ProductCard.tsx, client/src/components/ProductContent/ProductContent.tsx, client/src/components/UserContent/UserContent.tsx, client/src/pages/FormGenre/FormGenre.tsx, client/src/pages/FormLogin/FormLogin.tsx, client/src/pages/FormPlatform/FormPlatform.tsx, client/src/pages/FormProduct/FormProduct.tsx, client/src/pages/FormRegister/FormRegister.tsx, client/src/pages/FormReset/FormReset.tsx, client/src/pages/Home/Home.tsx, client/src/pages/OrderDetail/Step3/Step3.tsx, client/src/pages/ProductDetail/ProductDetail.tsx, client/src/pages/UserOrderDetail/UserOrderDetail.tsx, client/src/pages/UserPage/LeaveReview/LeaveReview.tsx, client/src/redux/actions/admin_actions.ts, client/src/redux/actions/auth_actions.ts, client/src/redux/actions/orders_action.ts, server/src/controllers/Product.js, server/src/controllers/User.js
algunos warning limpiados, quedan igual
=> feat(cleanwarnings)
